### PR TITLE
Add DQD Tutorial

### PR DESCRIPTION
**Pull request by Nivedit24**
## Description

    

Adding DQD Tutorial
https://colab.research.google.com/drive/1DCSFluMmquFPZ2rgUQWA44IPcu7EBfUJ#scrollTo=cr-94yAuzYns

- [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/icaros-usc/pyribs/blob/master/CONTRIBUTING.md)
- [x] I have formatted my code using `yapf`
- [x] I have tested my code by running `pytest`
- [x] I have linted my code with `pylint`
- [x] I have added a one-line description of my change to the changelog in `HISTORY.md`
- [x] This PR is ready to go

### CODE REVIEW

**Comment by LemonPi** [comment]
Hi I am interested in trying out DQD and it seems the dqd repository is deprecated in favor of pyribs. While this pull request hasn't been merged, is there a reason why the collab link you posted is private? I'd like to see how to use the  GradientArborescenceEmitter (which should implement CMA-MEGA).

**Comment by btjanaka** [comment]
> Hi I am interested in trying out DQD and it seems the dqd repository is deprecated in favor of pyribs. While this pull request hasn't been merged, is there a reason why the collab link you posted is private? I'd like to see how to use the GradientArborescenceEmitter (which should implement CMA-MEGA).

Hi @LemonPi, the notebook in the private Colab link you mentioned syncs to this GitHub repository, so you can still download the notebook from GitHub. You can also view the notebook using Colab's ability to access public GitHub notebooks; see this link: https://colab.research.google.com/github/icaros-usc/pyribs/blob/dqdTutorial/examples/tutorials/DQDTutorial.ipynb

If you need an example of DQD immediately, I recommend looking at the sphere example, specifically this line: https://github.com/icaros-usc/pyribs/blob/master/examples/sphere.py#L267 Also pay attention to the use of `ask_dqd` and `tell_dqd` when calling the scheduler.

Note that the tutorial is a huge work-in-progress. I'm not sure when it will be ready since it is finals season for us here at USC, but keep an eye on this thread and you should see a notification when it's merged.

Cheers :)

**Review by btjanaka — CHANGES_REQUESTED** [review]
Hi Nivedit, great job! The tutorial looks a lot cleaner. I have a few minor changes for you to make:

1. Clear the outputs from the installation cells so they don't clog up the documentation.
2. Define the result_archive right after the archive
3. Move the various components out of functions; since this is a tutorial, it's okay to have them just be global variables
4. Talk about what the bounds of the measure space mean for the archive.
5. Modify the tutorial as appropriate to say we are using CMA-MAEGA (rather than CMA-MEGA). Also create a list of things you would need to do to convert from CMA-MAEGA to CMA-MEGA (base this off the CMA-ME vs CMA-MAE differences here https://docs.pyribs.org/en/latest/tutorials/cma_mae.html#summary-differences-between-cma-me-and-cma-mae)
6. Take out the QD score and just report the mean objective; the QD score doesn't mean much because it goes negative. We could also add a qd_score_offset to the archive but then the QD score isn't very meaningful.
7. Can you change the indentation level to four spaces? This will make it consistent with our other tutorials and the rest of pyribs. I believe Colab has an option to do this.
8. Change STYLEGAN to StyleGAN in the conclusion.

Thank you!

**Review by itsdawei — CHANGES_REQUESTED** [review]
Another note: use "pyribs" instead of "Pyribs"

Great work!

**Review by btjanaka — APPROVED** [review]

**Comment by btjanaka** [comment]
Hi @Nivedit24, thank you for helping us implement this tutorial! I'm glad to say it's now merged.

**Pull request merged**
